### ISSUE TITLE
Error: failed to download "openstf" (hint: running `helm repo update` may help)

### ISSUE THREAD

**Issue by zedtux** [agoda-com/android-farm#1]
First of all, thank you for this looking promising awesome tool ! 👍 

I have a running k8s with a GitLab CI Runner, and I'm building a React-Native app with an iOS and Android version.

Looking around to get the Android tests running, I found `android-farm` (stars shining in my eyes).
So I immediately tried it :

```
$ helm install openstf
Error: failed to download "openstf" (hint: running `helm repo update` may help)

$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "gitlab" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

$ helm install openstf
Error: failed to download "openstf" (hint: running `helm repo update` may help)
```

Oops ... 😞. What am I missing here?

**Comment by Malinskiy** [comment]
@zedtux Hey mate. 

Firstly, you need to clone the repo first, `git clone` should help you with that.
The chart is not in the official repositories, so you install it from the repo>

Secondly, deployment on public cloud is not supported due to the fact the emulators will not be able start there unless you have nested virtualisation support. You should check if KVM is available for the nodes of your cluster. Real devices are also problematic to connect to public clouds.

I'm closing this issue, if you have any other problem - feel free to reopen a ticket or create a new one.
Cheers.

**Comment by zedtux** [comment]
Hey @Malinskiy,

Thank your for your quick reply ! 👍 

> The chart is not in the official repositories, so you install it from the repo>

Oh, that's what I was missing !

> You should check if KVM is available for the nodes of your cluster.

How can I do that?

> Real devices are also problematic to connect to public clouds.

That's fine, I'm looking for emulators only.

**Comment by Malinskiy** [comment]
@zedtux [kvm-ok](http://manpages.ubuntu.com/manpages/bionic/man1/kvm-ok.1.html) would be my choice

**Comment by zedtux** [comment]
Thank you @Malinskiy for your help. Unfortunately :

```
# kvm-ok
INFO: Your CPU does not support KVM extensions
KVM acceleration can NOT be used
```

Does this mean I have no way to get the android emulator running on my CI?
What are the options to get this working?

**Comment by Malinskiy** [comment]
@zedtux it seems like it's not possible using your current setup. usually it's due to the fact that nodes that public clouds are using are not barebone and even though the actual hardware may support it getting the virtualisation working inside an already virtualised environment is quite hard and also slow.

The setups of android-farm that I know of use real hardware that companies own, in other words you should have some hardware that you have full access to that you can dedicate for this project. This can also be on public clouds like GCE but costs are much higher.

Another option that I can think of is using emulator without hardware acceleration, but this will be super-slow and it will require some customisation in docker-emulator-android.

**Comment by zedtux** [comment]
Thank you for your comment @Malinskiy 👍. Well I have a Macmini for running my tests for iOS (not yet setup).
Could it be an option to bring it to my Kubernetes cluster and have android-farm working here or do you see problems with that?

**Comment by Malinskiy** [comment]
If you will join it to k8s cluster then it will work :) Don't forget to add labels and taint the nodes for the emulator as specified in the README
